### ISSUE TITLE
Color difference between NativeOSX and FFMPEG plugins

### ISSUE THREAD

**Issue by sh0sh1n** [databrary/datavyu-ffmpegplugin#150]
See screenshots.
<img width="872" alt="screen shot 2019-03-06 at 4 25 20 pm" src="https://user-images.githubusercontent.com/1036484/53918913-68ab9e00-4036-11e9-95c5-36eff8fbc06d.png">

QuickTime:
![framecolor-quicktime](https://user-images.githubusercontent.com/1036484/53918924-6ea17f00-4036-11e9-90cb-ae39fe386cdf.png)

VLC:
<img width="1948" alt="framecolor-vlc" src="https://user-images.githubusercontent.com/1036484/53918932-74976000-4036-11e9-9476-5e9b75c791ab.png">

**Comment by TheoWolf** [comment]
@Xubes Could you please check if this problem still in 0.20 version (Available in Datavyu 1.5.0 RC3)

**Comment by TheoWolf** [comment]
@Xubes Please review this ticket with the new SDL player (FFmpeg plugin version 0.22 = Datavyu 1.5.0-RC4
)
