### ISSUE TITLE
Video playback slower than normal speed at 1x

### ISSUE THREAD

**Issue by Xubes** [databrary/datavyu-ffmpegplugin#165]
While testing Datavyu v1.5.0-rc2: FFMPEG playback is slower than the NativeOSX plugin for the same video when playing at 1x speed.

Adding multiple instances of the same video using the FFMPEG further slows down the playback performance. This is not the case for the NativeOSX plugin.

**Comment by TheoWolf** [comment]
This is due to the canvas drawImage method that is not as fast as the FFmpeg engine, and this makes the Java side skip some frames and causes the lagging.

**Comment by TheoWolf** [comment]
This is fixed in #166
